### ISSUE TITLE
fails to recognize as Hetzner datacenter

### ISSUE THREAD

**Issue by jogaco** [kickstarter/ipcat-ruby#15]
According to this
http://144.76.96.86.ipaddress.com/

144.76.96.86 comes from Hetzner.
However:
```
IPCat.datacenter? '144.76.96.86'
 => nil 

```

**Comment by frewsxcv** [comment]
Our dataset is based off the data in https://github.com/client9/ipcat. Thanks for opening the issue, but this should be reported upstream
