### ISSUE TITLE
Helping out maintaining 

### ISSUE THREAD

**Issue by wallin** [kickstarter/ipcat-ruby#17]
This project looks like it could use some help with keeping it up to date, both with handling PRs as well as syncing with the datacenter source on a regular basis. 

I'd be happy to help out maintaining

**Comment by wallin** [comment]
Hey @ktheory, any thoughts? I'd be happy to help out keeping this gem up to date. Thanks!

**Comment by frewsxcv** [comment]
Hey @wallin, thanks for reaching out! I work at Kickstarter and would love to help maintain this. I just gotta double check with a couple people before merging any changes here, thanks for being patient :)

**Comment by wallin** [comment]
@frewsxcv awesome thanks! I totally understand if you guys don't have time to attend all incoming PRs so I'd be happy to take the load off, if you trust me to take care of it :) my plan was also to run the update regularly against the original dataset

**Comment by frewsxcv** [comment]
FYI, this is something I plan to bring up with coworkers next week, in case you don't see a response from me for a few days

**Comment by frewsxcv** [comment]
Thanks for bringing this up! I'll try to update the data here regularly. I just pushed a new version.

**Comment by wallin** [comment]
Thanks @frewsxcv!
