### ISSUE TITLE
Licence missing in the rubygems version and in the gemspec

### ISSUE THREAD

**Issue by mensfeld** [kickstarter/ipcat-ruby#24]
The "ipcat" gem seems not to have a license at all. Unless a license that specifies otherwise is included, nobody else can use, copy, distribute, or modify that library without being at risk of take-downs, shake-downs, or litigation.

I know, that this gem has a license on github, however it's missing one at rubygems and in a gemspec.

![zrzut ekranu z 2018-04-12 15 57 19](https://user-images.githubusercontent.com/392754/38681970-44888ab6-3e6a-11e8-8af5-05226c277317.png)

**Comment by frewsxcv** [comment]
thanks for pointing this out! this should be addressed in https://github.com/kickstarter/ipcat-ruby/commit/fe057e643b6f13bee08ca386671f99fd4f9c4c4d. i also published a new version.

**Comment by mensfeld** [comment]
@frewsxcv Thank you.
