### ISSUE TITLE
Upstream source is stale: Consider switching to https://github.com/rale/ipcat

### ISSUE THREAD

**Issue by garrow** [kickstarter/ipcat-ruby#26]
See: https://github.com/rale/ipcat

**Comment by amancevice** [comment]
linking for convenience: https://github.com/rale/ipcat

**Comment by amancevice** [comment]
@talaris instead of generating [`data/datacenters'](./data/datacenters) using HTTP, what are your thoughts on adding a submodule to the rale/ipcat repo and updating the rake task to look there?
