### ISSUE TITLE
Question about usage with rack attack in production

### ISSUE THREAD

**Issue by ritec** [kickstarter/ipcat-ruby#36]
Hello there good people of Kickstarter. This is more of a question than an issue, but some time ago I ran into the following article: https://kickstarter.engineering/rack-attack-protection-from-abusive-clients-4c188496293b
Which said, and I quote: 

> We also use the [IPCat ruby library](https://github.com/kickstarter/ipcat-ruby) to detect requests from well-known datacenters. You could block login attempts from datacenters with this: 

```
Rack::Attack.blacklist('bad_login_ip') { |req|
  req.post? && req.path == "/session" && IPCat.datacenter?(req.ip))
}
```

I am curious, is this actually the case in production? Do you ever block legitimate users? I am exploring implementing something similar.

**Comment by sixtyfive** [comment]
Are you sure you didn't want to ask this over at https://github.com/rack/rack-attack, @ritec ?

**Comment by ritec** [comment]
@sixtyfive No, it was more a question for the Kickstarter team. As it turns out, in my case, I would not have wanted to do that. I have since solved most of my issues with bots (for now). Thanks.
